//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yaojiang.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yaojiang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _019da7d618eb888427b5fbf1bd5dc496 {
            get {
                object obj = ResourceManager.GetObject("019da7d618eb888427b5fbf1bd5dc496", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _0a055567fdf6799fb0e71e6a809a4c9d {
            get {
                object obj = ResourceManager.GetObject("0a055567fdf6799fb0e71e6a809a4c9d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _0bd39583c3d67b4dcf7c46623222ae16 {
            get {
                object obj = ResourceManager.GetObject("0bd39583c3d67b4dcf7c46623222ae16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _0ecd92b33839e24771399a64ce9b0726 {
            get {
                object obj = ResourceManager.GetObject("0ecd92b33839e24771399a64ce9b0726", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _0fe46e3b93a734170d7ba71fe7604a9d {
            get {
                object obj = ResourceManager.GetObject("0fe46e3b93a734170d7ba71fe7604a9d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1251c9297cf23e106caeb6a26a1e505c {
            get {
                object obj = ResourceManager.GetObject("1251c9297cf23e106caeb6a26a1e505c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _14b04aa087e748f47a29c0d6ca7e0814 {
            get {
                object obj = ResourceManager.GetObject("14b04aa087e748f47a29c0d6ca7e0814", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _17707a8b43279985be92f893965f6131 {
            get {
                object obj = ResourceManager.GetObject("17707a8b43279985be92f893965f6131", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _20150410103419805_easyicon_net_16 {
            get {
                object obj = ResourceManager.GetObject("20150410103419805_easyicon_net_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _20150410103527182_easyicon_net_16 {
            get {
                object obj = ResourceManager.GetObject("20150410103527182_easyicon_net_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _20150410103612647_easyicon_net_24 {
            get {
                object obj = ResourceManager.GetObject("20150410103612647_easyicon_net_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _308d8400253f55289138c0b2e1a6e5f1 {
            get {
                object obj = ResourceManager.GetObject("308d8400253f55289138c0b2e1a6e5f1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _32fa828ba61ea8d3dc34ce1e950a304e251f5891 {
            get {
                object obj = ResourceManager.GetObject("32fa828ba61ea8d3dc34ce1e950a304e251f5891", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _344c9f49366c092ab7499353a37f7cf6 {
            get {
                object obj = ResourceManager.GetObject("344c9f49366c092ab7499353a37f7cf6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _3d14a103f67cb3f7b08555096c8959d0 {
            get {
                object obj = ResourceManager.GetObject("3d14a103f67cb3f7b08555096c8959d0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _41408669f8c2119491b40d755a8aa3c8 {
            get {
                object obj = ResourceManager.GetObject("41408669f8c2119491b40d755a8aa3c8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _47ddd627d9336d380d98a0b2e89224e5 {
            get {
                object obj = ResourceManager.GetObject("47ddd627d9336d380d98a0b2e89224e5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4a11c472c6158979ef61ccdf2069de9b {
            get {
                object obj = ResourceManager.GetObject("4a11c472c6158979ef61ccdf2069de9b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4b7154738fef07d209d7c6ede2133d48 {
            get {
                object obj = ResourceManager.GetObject("4b7154738fef07d209d7c6ede2133d48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4c9d3f77afb4e2c23262a87c4ffe999a {
            get {
                object obj = ResourceManager.GetObject("4c9d3f77afb4e2c23262a87c4ffe999a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4fff3577d1e768d0f43f7e79235b5d05 {
            get {
                object obj = ResourceManager.GetObject("4fff3577d1e768d0f43f7e79235b5d05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5c718fc2f931cb4f9fe7a5ea2ae54a75 {
            get {
                object obj = ResourceManager.GetObject("5c718fc2f931cb4f9fe7a5ea2ae54a75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _60cc11b3ce8cad87f2c71a23938b6cab {
            get {
                object obj = ResourceManager.GetObject("60cc11b3ce8cad87f2c71a23938b6cab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _6a71802d4fede17f0df5a92530f102f5 {
            get {
                object obj = ResourceManager.GetObject("6a71802d4fede17f0df5a92530f102f5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _6bedebe9d453919c5af92be5954efcbc {
            get {
                object obj = ResourceManager.GetObject("6bedebe9d453919c5af92be5954efcbc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _6f95b6f998f1ea15a4aac0056ce593b0 {
            get {
                object obj = ResourceManager.GetObject("6f95b6f998f1ea15a4aac0056ce593b0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _703ebf2fcce9d27f104979522764e3fe {
            get {
                object obj = ResourceManager.GetObject("703ebf2fcce9d27f104979522764e3fe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _79e59d3b3bb6280437662995c772c4e8 {
            get {
                object obj = ResourceManager.GetObject("79e59d3b3bb6280437662995c772c4e8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _7eedbc57446fdbfd21b8d7359513c4f8 {
            get {
                object obj = ResourceManager.GetObject("7eedbc57446fdbfd21b8d7359513c4f8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _803f786af73db6348710f18ddf3017d5 {
            get {
                object obj = ResourceManager.GetObject("803f786af73db6348710f18ddf3017d5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _836bf42b2cad9b42b8e6904b9dd28fb9 {
            get {
                object obj = ResourceManager.GetObject("836bf42b2cad9b42b8e6904b9dd28fb9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _8527d2bd369bc9416989ecbea77f0a98 {
            get {
                object obj = ResourceManager.GetObject("8527d2bd369bc9416989ecbea77f0a98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _8706e9d14ff735461c42200c07a0a97b {
            get {
                object obj = ResourceManager.GetObject("8706e9d14ff735461c42200c07a0a97b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _954a14cfd0a9ca7bbe2b1649bcb57cde {
            get {
                object obj = ResourceManager.GetObject("954a14cfd0a9ca7bbe2b1649bcb57cde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _95dbe1bad73c7f8f3143c6765fe46960 {
            get {
                object obj = ResourceManager.GetObject("95dbe1bad73c7f8f3143c6765fe46960", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _98ffb3d282b950a81c0d1edc917bdff7 {
            get {
                object obj = ResourceManager.GetObject("98ffb3d282b950a81c0d1edc917bdff7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _9b4e252e337175d9453a885fbc5d38ad {
            get {
                object obj = ResourceManager.GetObject("9b4e252e337175d9453a885fbc5d38ad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _9e8566daec91ce456a51ae44a7dd1f5a {
            get {
                object obj = ResourceManager.GetObject("9e8566daec91ce456a51ae44a7dd1f5a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _9fde76af5c9fe3e80f7b5df125607081 {
            get {
                object obj = ResourceManager.GetObject("9fde76af5c9fe3e80f7b5df125607081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap a6115383994746327ed8f1c40e2653f2 {
            get {
                object obj = ResourceManager.GetObject("a6115383994746327ed8f1c40e2653f2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap a89920abbc076cb6dca8a49fbae6d719 {
            get {
                object obj = ResourceManager.GetObject("a89920abbc076cb6dca8a49fbae6d719", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap aac519255003ec9b9836b93fdb2f1795 {
            get {
                object obj = ResourceManager.GetObject("aac519255003ec9b9836b93fdb2f1795", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap b180957b8cdcd427972622aff02bd3e0 {
            get {
                object obj = ResourceManager.GetObject("b180957b8cdcd427972622aff02bd3e0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap b35f8787b1dcb697de2475894845d35e {
            get {
                object obj = ResourceManager.GetObject("b35f8787b1dcb697de2475894845d35e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap b93bcd68ae44f690d90754363d0700a5 {
            get {
                object obj = ResourceManager.GetObject("b93bcd68ae44f690d90754363d0700a5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap b9d53aa2624e83e9217bbe5d87609dc6 {
            get {
                object obj = ResourceManager.GetObject("b9d53aa2624e83e9217bbe5d87609dc6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bbc3c43e792a26b18afd55afb14d580e {
            get {
                object obj = ResourceManager.GetObject("bbc3c43e792a26b18afd55afb14d580e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap bfa5c583e17881224f34b305265fe916 {
            get {
                object obj = ResourceManager.GetObject("bfa5c583e17881224f34b305265fe916", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap c215958673aaf14f93c73465a87b71a5 {
            get {
                object obj = ResourceManager.GetObject("c215958673aaf14f93c73465a87b71a5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap c53037182acd4be60010541937a83f5e {
            get {
                object obj = ResourceManager.GetObject("c53037182acd4be60010541937a83f5e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ce3c14d82140834c19b7c9d2c1afb07d {
            get {
                object obj = ResourceManager.GetObject("ce3c14d82140834c19b7c9d2c1afb07d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap d42942d43629b8bacb1481e16d922a90 {
            get {
                object obj = ResourceManager.GetObject("d42942d43629b8bacb1481e16d922a90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap dad11357a37bece33aa28ec6cad7913e {
            get {
                object obj = ResourceManager.GetObject("dad11357a37bece33aa28ec6cad7913e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ea025104d426aec477e1e4035743b8b0 {
            get {
                object obj = ResourceManager.GetObject("ea025104d426aec477e1e4035743b8b0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ea23722d55fea55b8c3f49fa6a923682 {
            get {
                object obj = ResourceManager.GetObject("ea23722d55fea55b8c3f49fa6a923682", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f18d9d27cba97eb784f7cb65a66247d9 {
            get {
                object obj = ResourceManager.GetObject("f18d9d27cba97eb784f7cb65a66247d9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f34b606ada7fbc98d828337db517636e {
            get {
                object obj = ResourceManager.GetObject("f34b606ada7fbc98d828337db517636e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f47f969a689c90cd03977e6b8aca2e1e {
            get {
                object obj = ResourceManager.GetObject("f47f969a689c90cd03977e6b8aca2e1e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap f7573934b37fcf5b41dd1d3df8a29e9b {
            get {
                object obj = ResourceManager.GetObject("f7573934b37fcf5b41dd1d3df8a29e9b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap fcb6b6a185fab26d2fa414aac780a3a6 {
            get {
                object obj = ResourceManager.GetObject("fcb6b6a185fab26d2fa414aac780a3a6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0018 {
            get {
                object obj = ResourceManager.GetObject("IMG_0018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0019 {
            get {
                object obj = ResourceManager.GetObject("IMG_0019", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0020 {
            get {
                object obj = ResourceManager.GetObject("IMG_0020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0336 {
            get {
                object obj = ResourceManager.GetObject("IMG_0336", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0338 {
            get {
                object obj = ResourceManager.GetObject("IMG_0338", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0339 {
            get {
                object obj = ResourceManager.GetObject("IMG_0339", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0340 {
            get {
                object obj = ResourceManager.GetObject("IMG_0340", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0341 {
            get {
                object obj = ResourceManager.GetObject("IMG_0341", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0342 {
            get {
                object obj = ResourceManager.GetObject("IMG_0342", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0343 {
            get {
                object obj = ResourceManager.GetObject("IMG_0343", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0344 {
            get {
                object obj = ResourceManager.GetObject("IMG_0344", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0345 {
            get {
                object obj = ResourceManager.GetObject("IMG_0345", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0346 {
            get {
                object obj = ResourceManager.GetObject("IMG_0346", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0347 {
            get {
                object obj = ResourceManager.GetObject("IMG_0347", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0348 {
            get {
                object obj = ResourceManager.GetObject("IMG_0348", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0349 {
            get {
                object obj = ResourceManager.GetObject("IMG_0349", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0350 {
            get {
                object obj = ResourceManager.GetObject("IMG_0350", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0351 {
            get {
                object obj = ResourceManager.GetObject("IMG_0351", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0353 {
            get {
                object obj = ResourceManager.GetObject("IMG_0353", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap IMG_0354 {
            get {
                object obj = ResourceManager.GetObject("IMG_0354", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap softmgr_notify {
            get {
                object obj = ResourceManager.GetObject("softmgr_notify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
